server:
  port: 80
  error:
    whitelabel:
      enabled: true
  tomcat:
    accesslog:
      enabled: true
      pattern: \t%{yyyy-MM-dd HH:mm:ss}t\t%s\t%r\t%{User-Agent}i\t%{Referer}i\t%a\t%b

logging:
  level:
    root: warn
    web: debug
  path: ./log/versioning
  file:
    max-size: 1MB